/**
 * Pre-encoded reference image for aspect ratio guidance
 * 
 * 50x70 PNG (2:3 aspect ratio) - TINY version - only 1.2KB
 * Used to guide Gemini to generate portrait-oriented images
 * Cost: ~$0.0002 per generation (negligible)
 * 
 * Tested with gemini-2.5-flash-image (stable model)
 * Results: Inconsistent - sometimes generates portrait (~2.4MB), sometimes square (~1.7MB)
 * Success rate: ~20% portrait in production (despite 100% in isolated tests)
 * Savings: 77% smaller than original 350x490 reference
 * 
 * NOTE: Gemini 2.5's aspect ratio control is unreliable as of 2025-01-17.
 * Neither config parameters nor reference images provide consistent results.
 * This is a known limitation of the current model version.
 */
export const REFERENCE_IMAGE_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAADIAAABGCAYAAACOjMdmAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAhGVYSWZNTQAqAAAACAAFARIAAwAAAAEAAQAAARoABQAAAAEAAABKARsABQAAAAEAAABSASgAAwAAAAEAAgAAh2kABAAAAAEAAABaAAAAAAAAAEgAAAABAAAASAAAAAEAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAMqADAAQAAAABAAAARgAAAACKo4SnAAAACXBIWXMAAAsTAAALEwEAmpwYAAACymlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNi4wLjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgICAgICAgICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iPgogICAgICAgICA8dGlmZjpZUmVzb2x1dGlvbj43MjwvdGlmZjpZUmVzb2x1dGlvbj4KICAgICAgICAgPHRpZmY6UmVzb2x1dGlvblVuaXQ+MjwvdGlmZjpSZXNvbHV0aW9uVW5pdD4KICAgICAgICAgPHRpZmY6WFJlc29sdXRpb24+NzI8L3RpZmY6WFJlc29sdXRpb24+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj4zNTA8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpDb2xvclNwYWNlPjE8L2V4aWY6Q29sb3JTcGFjZT4KICAgICAgICAgPGV4aWY6UGl4ZWxZRGltZW5zaW9uPjQ5MDwvZXhpZjpQaXhlbFlEaW1lbnNpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgrfLnW3AAAA1klEQVRoBe2SyQmAQBTF3PrvznLErYRABpF4fxl+4nze3/SDb/nBDe8JHfK1khWpiGSgX0sSi7EVweqkYUUksRhbEaxOGlZEEouxFcHqpGFFJLEYWxGsThpWRBKLsRXB6qRhRSSxGFsRrE4aVkQSi7EVweqkYUUksRhbEaxOGlZEEouxFcHqpGFFJLEYWxGsThpWRBKLsRXB6qRhRSSxGFsRrE4aVkQSi7EVweqkYUUksRhbEaxOGlZEEouxFcHqpOF2cw+JPRT7HLIOfVF67Dlkl9hDsRdASQZjeHin9AAAAABJRU5ErkJggg==';
